name: PokemonTracker
options:
  bundleIdPrefix: com.pokemontracker
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  PokemonTracker:
    type: application
    platform: iOS
    sources:
      - path: PokemonTracker
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSCameraUsageDescription: "We need camera access to scan your Pokemon cards"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "We need photo library access to scan cards from your photos"
        PRODUCT_BUNDLE_IDENTIFIER: com.pokemontracker.app
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - package: Supabase
        product: Supabase
    entitlements:
      path: PokemonTracker/PokemonTracker.entitlements
      properties:
        com.apple.security.app-sandbox: true
        aps-environment: development
